### ISSUE TITLE
Total amount in letters fails with "un mil"

### ISSUE THREAD

**Issue by Liiz** [Sistrategia/SistrategiaCFDi#29]
Total amount: 41,934.00
Shows: "CUARENTA Y U MIL NOVECIENTOS TREINTA Y CUATRO"
Should be: "CUARENTA Y UN MIL NOVECIENTOS TREINTA Y CUATRO"
Folio A228

**Comment by eocampo** [comment]
El error debe estar aquí:

https://github.com/Sistrategia/SistrategiaCFDi/blob/af36e6263f39813c51b0952c95d3370f7a44993f/src/Sistrategia.SAT.CFDiWebSite/CFDI/CantidadEnLetraConverter.cs
